### ISSUE TITLE
请问大神，现在这个能抢到票吗？准备用g口服务器试试

### ISSUE THREAD

**Issue by m9rco** [2645Corp/Q12306#1]
请问大神，现在这个能抢到票吗？准备用g口服务器试试

**Comment by satouriko** [comment]
不能呀😂 这个还没开发好呢。。 不知道为什么我用它登录一直提示服务器繁忙 现在还没解决 我已经买飞机票了😂

**Comment by m9rco** [comment]
好吧，我拜托飞猪抢了，抢不到也走机票算了
